# Generated by Django 3.1.4 on 2021-01-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210103_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличе SD карты'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный обьем памяти'),
        ),
    ]
